schema = {
    'name':{'type':'string','required': True},
    'email':{'type':'string','required': True},
    'college':{'type':'string'},
    'location':{'type':'string'},
    'highest_qualification':{'type':'string'},
    'tenth_name':{'type':'string'},
    'tenth_marks':{'type':'integer'},
    'twelfth_name':{'type':'string'},
    'twelfth_marks':{'type':'integer'},
    'UG_degree':{'type':'string'},
    'UG_marks':{'type':'integer'},
    'UG_institution_name':{'type':'string'},
    'PG_degree':{'type':'string'},
    'PG_marks':{'type':'integer'},
    'PG_institution_name':{'type':'string'},
    'category':{'type':'integer'},
    # 'user_id':{'type':'integer'},
    'intrested_areas':{'type':'string','required': True},
}